version: '3.9'
services:
  database:
    image: postgres
    container_name: ib-university-project
    ports:
      - '5438:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: university_db

volumes:
  pg-data:
